"""Contenido por niveles (Inicial, Básico, Intermedio). Para agregar más, copie un bloque y cambie los textos.

Cada tema tiene frases (inglés, español) y una conversación.
En la conversación, "A" es la aplicación y "B" es la persona que practica.
"""

_RAW = [
    ("Saludos", "👋", [
        ("Hi, how are you?", "Hola, ¿cómo estás?"),
        ("I'm fine, thank you.", "Estoy bien, gracias."),
        ("What's your name?", "¿Cómo te llamas?"),
        ("Nice to meet you.", "Mucho gusto."),
        ("Where are you from?", "¿De dónde eres?"),
        ("I'm from Colombia.", "Soy de Colombia."),
        ("Can you repeat that, please?", "¿Puedes repetir, por favor?"),
        ("See you tomorrow.", "Nos vemos mañana."),
    ], [
        ("A", "Hi! How are you?", "¡Hola! ¿Cómo estás?"),
        ("B", "I'm fine, thank you.", "Estoy bien, gracias."),
        ("A", "Where are you from?", "¿De dónde eres?"),
        ("B", "I'm from Colombia.", "Soy de Colombia."),
        ("A", "Nice to meet you!", "¡Mucho gusto!"),
        ("B", "Nice to meet you too. See you tomorrow.", "Mucho gusto también. Nos vemos mañana."),
    ]),
    ("Familia y casa", "🏠", [
        ("This is my family.", "Esta es mi familia."),
        ("I have two brothers.", "Tengo dos hermanos."),
        ("My mother is at home.", "Mi mamá está en casa."),
        ("We live in a small house.", "Vivimos en una casa pequeña."),
        ("Where is the bathroom?", "¿Dónde está el baño?"),
        ("The kitchen is over there.", "La cocina está allá."),
        ("I love my family.", "Amo a mi familia."),
        ("Who is that?", "¿Quién es ese?"),
    ], [
        ("A", "Do you have brothers or sisters?", "¿Tienes hermanos o hermanas?"),
        ("B", "Yes, I have two brothers.", "Sí, tengo dos hermanos."),
        ("A", "Where do you live?", "¿Dónde vives?"),
        ("B", "We live in a small house.", "Vivimos en una casa pequeña."),
        ("A", "Who is at home now?", "¿Quién está en casa ahora?"),
        ("B", "My mother is at home.", "Mi mamá está en casa."),
    ]),
    ("Comida", "🍎", [
        ("I'm hungry.", "Tengo hambre."),
        ("I would like some water, please.", "Quisiera un poco de agua, por favor."),
        ("Can I have the menu?", "¿Me da el menú?"),
        ("I like chicken and rice.", "Me gusta el pollo con arroz."),
        ("What do you want to eat?", "¿Qué quieres comer?"),
        ("The food is very good.", "La comida está muy buena."),
        ("How much is it?", "¿Cuánto es?"),
        ("The check, please.", "La cuenta, por favor."),
    ], [
        ("A", "Hello! What do you want to eat?", "¡Hola! ¿Qué quieres comer?"),
        ("B", "I like chicken and rice.", "Me gusta el pollo con arroz."),
        ("A", "Anything to drink?", "¿Algo de tomar?"),
        ("B", "I would like some water, please.", "Quisiera un poco de agua, por favor."),
        ("A", "Here you go.", "Aquí tienes."),
        ("B", "Thank you. The food is very good.", "Gracias. La comida está muy buena."),
    ]),
    ("Rutina diaria", "⏰", [
        ("I wake up early.", "Me despierto temprano."),
        ("I take a shower every morning.", "Me ducho todas las mañanas."),
        ("I go to work by bus.", "Voy al trabajo en bus."),
        ("What time is it?", "¿Qué hora es?"),
        ("It's time to go to bed.", "Es hora de ir a la cama."),
        ("I'm very tired today.", "Estoy muy cansado hoy."),
        ("What are you doing?", "¿Qué estás haciendo?"),
        ("I'm doing my homework.", "Estoy haciendo mi tarea."),
    ], [
        ("A", "What time do you wake up?", "¿A qué hora te despiertas?"),
        ("B", "I wake up early.", "Me despierto temprano."),
        ("A", "How do you go to work?", "¿Cómo vas al trabajo?"),
        ("B", "I go to work by bus.", "Voy al trabajo en bus."),
        ("A", "What are you doing now?", "¿Qué estás haciendo ahora?"),
        ("B", "I'm doing my homework.", "Estoy haciendo mi tarea."),
    ]),
    ("En la calle", "🚌", [
        ("Excuse me, where is the bank?", "Disculpe, ¿dónde está el banco?"),
        ("Go straight and turn left.", "Siga derecho y gire a la izquierda."),
        ("Is it far from here?", "¿Está lejos de aquí?"),
        ("It's near the park.", "Está cerca del parque."),
        ("I need a taxi.", "Necesito un taxi."),
        ("How do I get to the airport?", "¿Cómo llego al aeropuerto?"),
        ("I'm lost. Can you help me?", "Estoy perdido. ¿Me puede ayudar?"),
        ("Thank you for your help.", "Gracias por su ayuda."),
    ], [
        ("A", "Can I help you?", "¿Le puedo ayudar?"),
        ("B", "Excuse me, where is the bank?", "Disculpe, ¿dónde está el banco?"),
        ("A", "Go straight and turn left.", "Siga derecho y gire a la izquierda."),
        ("B", "Is it far from here?", "¿Está lejos de aquí?"),
        ("A", "No, it's near the park.", "No, está cerca del parque."),
        ("B", "Thank you for your help.", "Gracias por su ayuda."),
    ]),
    ("Compras", "🛍️", [
        ("How much does this cost?", "¿Cuánto cuesta esto?"),
        ("It's too expensive.", "Es demasiado caro."),
        ("Do you have a bigger size?", "¿Tiene una talla más grande?"),
        ("I'm just looking, thanks.", "Solo estoy mirando, gracias."),
        ("I'll take it.", "Me lo llevo."),
        ("Can I pay with a card?", "¿Puedo pagar con tarjeta?"),
        ("Where can I buy shoes?", "¿Dónde puedo comprar zapatos?"),
        ("I need a new jacket.", "Necesito una chaqueta nueva."),
    ], [
        ("A", "Hello! Can I help you?", "¡Hola! ¿Le puedo ayudar?"),
        ("B", "I need a new jacket.", "Necesito una chaqueta nueva."),
        ("A", "This one is very nice.", "Esta es muy bonita."),
        ("B", "How much does this cost?", "¿Cuánto cuesta esto?"),
        ("A", "It's forty dollars.", "Cuesta cuarenta dólares."),
        ("B", "I'll take it. Can I pay with a card?", "Me lo llevo. ¿Puedo pagar con tarjeta?"),
    ]),
]

_L1 = [
    ("Hola y adiós", "👋", [
        ("Hello!", "¡Hola!"),
        ("Good morning.", "Buenos días."),
        ("Good night.", "Buenas noches."),
        ("Thank you.", "Gracias."),
        ("Yes, please.", "Sí, por favor."),
        ("No, thank you.", "No, gracias."),
        ("I'm sorry.", "Lo siento."),
        ("Goodbye!", "¡Adiós!"),
    ], [
        ("A", "Hello! Good morning.", "¡Hola! Buenos días."),
        ("B", "Good morning.", "Buenos días."),
        ("A", "Do you want some juice?", "¿Quieres jugo?"),
        ("B", "Yes, please.", "Sí, por favor."),
        ("A", "Here you go.", "Aquí tienes."),
        ("B", "Thank you. Goodbye!", "Gracias. ¡Adiós!"),
    ]),
    ("Colores", "🎨", [
        ("It's red.", "Es rojo."),
        ("It's blue.", "Es azul."),
        ("The sun is yellow.", "El sol es amarillo."),
        ("The tree is green.", "El árbol es verde."),
        ("I like pink.", "Me gusta el rosado."),
        ("Black and white.", "Negro y blanco."),
        ("I have two hands.", "Tengo dos manos."),
        ("What color is it?", "¿De qué color es?"),
    ], [
        ("A", "Look at the sun. What color is it?", "Mira el sol. ¿De qué color es?"),
        ("B", "The sun is yellow.", "El sol es amarillo."),
        ("A", "And the tree?", "¿Y el árbol?"),
        ("B", "The tree is green.", "El árbol es verde."),
        ("A", "What color do you like?", "¿Qué color te gusta?"),
        ("B", "I like pink.", "Me gusta el rosado."),
    ]),
    ("Animales", "🐶", [
        ("This is a dog.", "Este es un perro."),
        ("The cat is small.", "El gato es pequeño."),
        ("I see a bird.", "Veo un pájaro."),
        ("The lion is big.", "El león es grande."),
        ("Look, a duck!", "¡Mira, un pato!"),
        ("I like my dog.", "Me gusta mi perro."),
        ("The fish is in the water.", "El pez está en el agua."),
        ("It's a horse.", "Es un caballo."),
    ], [
        ("A", "What is this?", "¿Qué es esto?"),
        ("B", "This is a dog.", "Este es un perro."),
        ("A", "Is the cat big?", "¿El gato es grande?"),
        ("B", "No. The cat is small.", "No. El gato es pequeño."),
        ("A", "What do you see?", "¿Qué ves?"),
        ("B", "I see a bird.", "Veo un pájaro."),
    ]),
    ("Vamos a jugar", "🧸", [
        ("This is my ball.", "Esta es mi pelota."),
        ("Let's play!", "¡Vamos a jugar!"),
        ("I have a bike.", "Tengo una bicicleta."),
        ("It's my turn.", "Es mi turno."),
        ("I want to play.", "Quiero jugar."),
        ("Come with me.", "Ven conmigo."),
        ("I'm happy.", "Estoy feliz."),
        ("Look at me!", "¡Mírame!"),
    ], [
        ("A", "Hi! What do you want to do?", "¡Hola! ¿Qué quieres hacer?"),
        ("B", "I want to play.", "Quiero jugar."),
        ("A", "What is this?", "¿Qué es esto?"),
        ("B", "This is my ball.", "Esta es mi pelota."),
        ("A", "Great! Let's play!", "¡Genial! ¡Vamos a jugar!"),
        ("B", "It's my turn. I'm happy.", "Es mi turno. Estoy feliz."),
    ]),
]

_L3 = [
    ("Planes", "📅", [
        ("What are you going to do this weekend?", "¿Qué vas a hacer este fin de semana?"),
        ("I'm going to visit my grandparents.", "Voy a visitar a mis abuelos."),
        ("We went to the beach last month.", "Fuimos a la playa el mes pasado."),
        ("I didn't have time to call you.", "No tuve tiempo de llamarte."),
        ("Would you like to come with us?", "¿Te gustaría venir con nosotros?"),
        ("That sounds like a great idea.", "Suena como una gran idea."),
        ("I'll let you know tomorrow.", "Te aviso mañana."),
        ("I had a really good time.", "La pasé muy bien."),
    ], [
        ("A", "What are you going to do this weekend?", "¿Qué vas a hacer este fin de semana?"),
        ("B", "I'm going to visit my grandparents.", "Voy a visitar a mis abuelos."),
        ("A", "Nice. We are going to the beach. Would you like to come with us?", "Qué bien. Vamos a la playa. ¿Te gustaría venir con nosotros?"),
        ("B", "That sounds like a great idea.", "Suena como una gran idea."),
        ("A", "Can you tell me today?", "¿Me puedes decir hoy?"),
        ("B", "I'll let you know tomorrow.", "Te aviso mañana."),
    ]),
    ("Trabajo", "💼", [
        ("What do you do for a living?", "¿A qué te dedicas?"),
        ("I work in an office downtown.", "Trabajo en una oficina en el centro."),
        ("I've been working here for five years.", "Llevo cinco años trabajando aquí."),
        ("I have a meeting this afternoon.", "Tengo una reunión esta tarde."),
        ("Could you send me the report?", "¿Me podrías enviar el informe?"),
        ("I'm sorry, I'm running late.", "Lo siento, voy tarde."),
        ("Let me check and get back to you.", "Déjame revisar y te respondo."),
        ("I need to finish this before Friday.", "Necesito terminar esto antes del viernes."),
    ], [
        ("A", "What do you do for a living?", "¿A qué te dedicas?"),
        ("B", "I work in an office downtown.", "Trabajo en una oficina en el centro."),
        ("A", "How long have you worked there?", "¿Cuánto tiempo llevas trabajando ahí?"),
        ("B", "I've been working here for five years.", "Llevo cinco años trabajando aquí."),
        ("A", "Could you send me the report today?", "¿Me podrías enviar el informe hoy?"),
        ("B", "Let me check and get back to you.", "Déjame revisar y te respondo."),
    ]),
    ("Viajes", "✈️", [
        ("I'd like to book a room for two nights.", "Quisiera reservar una habitación por dos noches."),
        ("What time does the flight leave?", "¿A qué hora sale el vuelo?"),
        ("Could you tell me where the gate is?", "¿Me podría decir dónde está la puerta de embarque?"),
        ("I have a reservation under my name.", "Tengo una reserva a mi nombre."),
        ("Is breakfast included?", "¿El desayuno está incluido?"),
        ("How long does it take to get there?", "¿Cuánto se demora en llegar?"),
        ("I think I left my bag on the bus.", "Creo que dejé mi maleta en el bus."),
        ("Can you recommend a good restaurant?", "¿Me puede recomendar un buen restaurante?"),
    ], [
        ("A", "Good evening. How can I help you?", "Buenas noches. ¿En qué le puedo ayudar?"),
        ("B", "I have a reservation under my name.", "Tengo una reserva a mi nombre."),
        ("A", "Yes, here it is. A room for two nights.", "Sí, aquí está. Una habitación por dos noches."),
        ("B", "Is breakfast included?", "¿El desayuno está incluido?"),
        ("A", "Yes, it is. Anything else?", "Sí, está incluido. ¿Algo más?"),
        ("B", "Can you recommend a good restaurant?", "¿Me puede recomendar un buen restaurante?"),
    ]),
    ("Salud y problemas", "🩺", [
        ("I don't feel very well.", "No me siento muy bien."),
        ("I have a headache.", "Tengo dolor de cabeza."),
        ("I need to see a doctor.", "Necesito ver a un médico."),
        ("How long have you felt like this?", "¿Hace cuánto te sientes así?"),
        ("You should get some rest.", "Deberías descansar un poco."),
        ("My phone isn't working.", "Mi teléfono no funciona."),
        ("Could you speak more slowly, please?", "¿Podría hablar más despacio, por favor?"),
        ("I didn't understand the last part.", "No entendí la última parte."),
    ], [
        ("A", "Hello. What seems to be the problem?", "Hola. ¿Cuál parece ser el problema?"),
        ("B", "I don't feel very well. I have a headache.", "No me siento muy bien. Tengo dolor de cabeza."),
        ("A", "How long have you felt like this?", "¿Hace cuánto te sientes así?"),
        ("B", "Could you speak more slowly, please?", "¿Podría hablar más despacio, por favor?"),
        ("A", "Of course. You should get some rest and drink water.", "Claro. Deberías descansar y tomar agua."),
        ("B", "Thank you. I need to see a doctor.", "Gracias. Necesito ver a un médico."),
    ]),
]

_L1 += [('Mi familia',
  '👪',
  [('This is my mom.', 'Esta es mi mamá.'),
   ('This is my dad.', 'Este es mi papá.'),
   ('I have a sister.', 'Tengo una hermana.'),
   ('My brother is tall.', 'Mi hermano es alto.'),
   ('She is my friend.', 'Ella es mi amiga.'),
   ('We are a family.', 'Somos una familia.'),
   ('I love you.', 'Te quiero.'),
   ('Give me a hug.', 'Dame un abrazo.')],
  [('A', 'Who is this?', '¿Quién es?'),
   ('B', 'This is my mom.', 'Esta es mi mamá.'),
   ('A', 'Do you have a sister?', '¿Tienes una hermana?'),
   ('B', 'Yes. I have a sister.', 'Sí. Tengo una hermana.')]),
 ('Comida rica',
  '🍌',
  [('I like apples.', 'Me gustan las manzanas.'),
   ('I want milk.', 'Quiero leche.'),
   ("I'm hungry.", 'Tengo hambre.'),
   ("I'm thirsty.", 'Tengo sed.'),
   ("It's yummy!", '¡Está rico!'),
   ('More water, please.', 'Más agua, por favor.'),
   ("I don't like fish.", 'No me gusta el pescado.'),
   ('An orange juice, please.', 'Un jugo de naranja, por favor.')],
  [('A', 'Are you hungry?', '¿Tienes hambre?'),
   ('B', "Yes. I'm hungry.", 'Sí. Tengo hambre.'),
   ('A', 'What do you like?', '¿Qué te gusta?'),
   ('B', 'I like apples.', 'Me gustan las manzanas.')])]

_RAW += [('Clima y ropa',
  '☀️',
  [("It's sunny today.", 'Hoy está soleado.'),
   ("It's raining.", 'Está lloviendo.'),
   ("It's very cold.", 'Hace mucho frío.'),
   ('I need an umbrella.', 'Necesito un paraguas.'),
   ('Put on your jacket.', 'Ponte la chaqueta.'),
   ("I'm wearing a blue shirt.", 'Llevo puesta una camisa azul.'),
   ("What's the weather like?", '¿Cómo está el clima?'),
   ("It's hot outside.", 'Hace calor afuera.')],
  [('A', "What's the weather like?", '¿Cómo está el clima?'),
   ('B', "It's raining.", 'Está lloviendo.'),
   ('A', 'Do you have an umbrella?', '¿Tienes paraguas?'),
   ('B', 'No. I need an umbrella.', 'No. Necesito un paraguas.')]),
 ('Tiempo libre',
  '⚽',
  [('What do you do in your free time?', '¿Qué haces en tu tiempo libre?'),
   ('I like to play soccer.', 'Me gusta jugar fútbol.'),
   ('I watch movies at night.', 'Veo películas en la noche.'),
   ('I listen to music every day.', 'Escucho música todos los días.'),
   ('Do you want to go to the park?', '¿Quieres ir al parque?'),
   ("Let's go together.", 'Vamos juntos.'),
   ('I can swim very well.', 'Sé nadar muy bien.'),
   ("I can't play the guitar.", 'No sé tocar la guitarra.')],
  [('A', 'What do you do in your free time?', '¿Qué haces en tu tiempo libre?'),
   ('B', 'I like to play soccer.', 'Me gusta jugar fútbol.'),
   ('A', 'Do you want to go to the park?', '¿Quieres ir al parque?'),
   ('B', "Yes. Let's go together.", 'Sí. Vamos juntos.')])]

_L2B = [('Ayer y el pasado',
  '🕰️',
  [('What did you do yesterday?', '¿Qué hiciste ayer?'),
   ('I stayed at home all day.', 'Me quedé en casa todo el día.'),
   ('I went to the supermarket.', 'Fui al supermercado.'),
   ('We watched a movie last night.', 'Vimos una película anoche.'),
   ("I didn't go to school.", 'No fui al colegio.'),
   ('Did you have a good day?', '¿Tuviste un buen día?'),
   ('I saw my friends on Saturday.', 'Vi a mis amigos el sábado.'),
   ('It was a lot of fun.', 'Fue muy divertido.')],
  [('A', 'What did you do yesterday?', '¿Qué hiciste ayer?'),
   ('B', 'I went to the supermarket.', 'Fui al supermercado.'),
   ('A', 'Did you have a good day?', '¿Tuviste un buen día?'),
   ('B', 'Yes. It was a lot of fun.', 'Sí. Fue muy divertido.')]),
 ('En el restaurante',
  '🍽️',
  [('A table for four, please.', 'Una mesa para cuatro, por favor.'),
   ('Are you ready to order?', '¿Están listos para pedir?'),
   ("I'll have the soup, please.", 'Voy a pedir la sopa, por favor.'),
   ('Could we have some more bread?', '¿Nos trae un poco más de pan?'),
   ('This is delicious.', 'Esto está delicioso.'),
   ("I'm allergic to nuts.", 'Soy alérgico a las nueces.'),
   ('Can we have the check, please?', '¿Nos trae la cuenta, por favor?'),
   ('Do you take credit cards?', '¿Aceptan tarjetas de crédito?')],
  [('A', 'Good evening. Are you ready to order?', 'Buenas noches. ¿Están listos para pedir?'),
   ('B', "Yes. I'll have the soup, please.", 'Sí. Voy a pedir la sopa, por favor.'),
   ('A', 'Anything else?', '¿Algo más?'),
   ('B', 'Could we have some more bread?', '¿Nos trae un poco más de pan?'),
   ('A', 'Of course. Here you are.', 'Claro. Aquí tienen.'),
   ('B', 'This is delicious. Can we have the check, please?', 'Esto está delicioso. ¿Nos trae la cuenta, por favor?')]),
 ('Al teléfono',
  '📞',
  [('Hello, who is calling?', 'Hola, ¿quién llama?'),
   ('Can I speak to the manager?', '¿Puedo hablar con el gerente?'),
   ('Please hold on a moment.', 'Por favor espere un momento.'),
   ("I'll call you back later.", 'Te devuelvo la llamada más tarde.'),
   ('Can you hear me?', '¿Me escuchas?'),
   ('The line is busy.', 'La línea está ocupada.'),
   ('Could you repeat your number?', '¿Podría repetir su número?'),
   ('Sorry, I have the wrong number.', 'Perdón, número equivocado.')],
  [('A', 'Hello, who is calling?', 'Hola, ¿quién llama?'),
   ('B', 'Can I speak to the manager?', '¿Puedo hablar con el gerente?'),
   ('A', 'The line is busy. Can you wait?', 'La línea está ocupada. ¿Puede esperar?'),
   ('B', "No, thank you. I'll call you back later.", 'No, gracias. Devuelvo la llamada más tarde.')]),
 ('Describir personas',
  '🧑',
  [('What does she look like?', '¿Cómo es ella?'),
   ('She has long dark hair.', 'Tiene el pelo largo y oscuro.'),
   ('He is taller than me.', 'Él es más alto que yo.'),
   ('My sister is very friendly.', 'Mi hermana es muy amable.'),
   ('He is wearing glasses.', 'Él usa gafas.'),
   ('They are both very funny.', 'Los dos son muy divertidos.'),
   ('She looks like her mother.', 'Se parece a su mamá.'),
   ('He is the youngest in the family.', 'Es el menor de la familia.')],
  [('A', 'What does your sister look like?', '¿Cómo es tu hermana?'),
   ('B', 'She has long dark hair.', 'Tiene el pelo largo y oscuro.'),
   ('A', 'Is she friendly?', '¿Es amable?'),
   ('B', 'Yes. My sister is very friendly.', 'Sí. Mi hermana es muy amable.')]),
 ('Transporte',
  '🚇',
  [('Which bus goes downtown?', '¿Qué bus va al centro?'),
   ('Where do I get off?', '¿Dónde me bajo?'),
   ('It takes about twenty minutes.', 'Se demora unos veinte minutos.'),
   ('The station is across the street.', 'La estación está al otro lado de la calle.'),
   ('You need to change trains.', 'Tiene que cambiar de tren.'),
   ('Is this seat taken?', '¿Este puesto está ocupado?'),
   ('How much is a ticket?', '¿Cuánto cuesta un tiquete?'),
   ('I missed my bus this morning.', 'Perdí el bus esta mañana.')],
  [('A', 'Can I help you?', '¿Le puedo ayudar?'),
   ('B', 'Which bus goes downtown?', '¿Qué bus va al centro?'),
   ('A', 'The blue one. It takes about twenty minutes.', 'El azul. Se demora unos veinte minutos.'),
   ('B', 'Thank you. Where do I get off?', 'Gracias. ¿Dónde me bajo?')]),
 ('En casa',
  '🧹',
  [('Can you help me with the dishes?', '¿Me ayudas con los platos?'),
   ('I have to clean my room.', 'Tengo que limpiar mi cuarto.'),
   ('Dinner is almost ready.', 'La cena está casi lista.'),
   ('Turn off the lights, please.', 'Apaga las luces, por favor.'),
   ("I can't find my keys.", 'No encuentro mis llaves.'),
   ('Whose turn is it?', '¿A quién le toca?'),
   ("I'm going to take out the trash.", 'Voy a sacar la basura.'),
   ("Let's watch something together.", 'Veamos algo juntos.')],
  [('A', 'Dinner is almost ready. Can you help me?', 'La cena está casi lista. ¿Me ayudas?'),
   ('B', 'Sure. I have to clean my room first.', 'Claro. Primero tengo que limpiar mi cuarto.'),
   ('A', 'And who takes out the trash today?', '¿Y quién saca la basura hoy?'),
   ('B', "It's my turn. I'm going to take out the trash.", 'Me toca a mí. Voy a sacar la basura.')])]

_L3 += [('Opiniones',
  '💭',
  [('What do you think about it?', '¿Qué piensas de eso?'),
   ("In my opinion, it's too expensive.", 'En mi opinión, es demasiado caro.'),
   ('I agree with you.', 'Estoy de acuerdo contigo.'),
   ("I'm not sure about that.", 'No estoy seguro de eso.'),
   ('It depends on the price.', 'Depende del precio.'),
   ('I prefer to stay at home.', 'Prefiero quedarme en casa.'),
   ("That's a good point.", 'Ese es un buen punto.'),
   ("I've changed my mind.", 'Cambié de opinión.')],
  [('A', 'What do you think about the new plan?', '¿Qué piensas del nuevo plan?'),
   ('B', "In my opinion, it's too expensive.", 'En mi opinión, es demasiado caro.'),
   ('A', "It's not cheap, but it's very good.", 'No es barato, pero es muy bueno.'),
   ('B', "That's a good point. I've changed my mind.", 'Ese es un buen punto. Cambié de opinión.')]),
 ('Tiendas y bancos',
  '🏦',
  [("I'd like to return this, please.", 'Quisiera devolver esto, por favor.'),
   ('Do you have this in another color?', '¿Tiene esto en otro color?'),
   ("I'd like to open an account.", 'Quisiera abrir una cuenta.'),
   ('Could I get a refund?', '¿Me podrían devolver el dinero?'),
   ("It doesn't fit me.", 'No me queda bien.'),
   ("I'm looking for a gift for my mother.", 'Busco un regalo para mi mamá.'),
   ('When will it be ready?', '¿Cuándo estará listo?'),
   ('Is there a discount if I pay in cash?', '¿Hay descuento si pago en efectivo?')],
  [('A', 'Hello. How can I help you?', 'Hola. ¿En qué le puedo ayudar?'),
   ('B', "I'd like to return this, please.", 'Quisiera devolver esto, por favor.'),
   ('A', "What's the problem with it?", '¿Cuál es el problema?'),
   ('B', "It doesn't fit me. Could I get a refund?", 'No me queda bien. ¿Me podrían devolver el dinero?')])]

_L5 = [('Reuniones',
  '📊',
  [("Let's get started, shall we?", 'Empecemos, ¿les parece?'),
   ("I'd like to go over the main points.", 'Quisiera repasar los puntos principales.'),
   ('Could you walk me through the numbers?', '¿Me podrías explicar las cifras paso a paso?'),
   ("We're slightly behind schedule.", 'Estamos un poco atrasados.'),
   ("I'll follow up with an email this afternoon.", 'Les escribo un correo esta tarde.'),
   ('What I mean is that we need more time.', 'Lo que quiero decir es que necesitamos más tiempo.'),
   ('Does that make sense to everyone?', '¿Les queda claro a todos?'),
   ("Let's wrap it up for today.", 'Terminemos por hoy.')],
  [('A', 'Thanks for joining. How is the project going?', 'Gracias por venir. ¿Cómo va el proyecto?'),
   ('B', "We're slightly behind schedule.", 'Estamos un poco atrasados.'),
   ('A', 'What do you need from us?', '¿Qué necesitan de nosotros?'),
   ('B', 'What I mean is that we need more time.', 'Lo que quiero decir es que necesitamos más tiempo.')]),
 ('Contar una historia',
  '📖',
  [("You won't believe what happened to me.", 'No vas a creer lo que me pasó.'),
   ('I was walking home when it started to rain.', 'Iba caminando a casa cuando empezó a llover.'),
   ('It turned out to be a misunderstanding.', 'Resultó ser un malentendido.'),
   ('I had never seen anything like it.', 'Nunca había visto algo así.'),
   ('In the end, everything worked out fine.', 'Al final, todo salió bien.'),
   ('To make a long story short, we missed the flight.', 'Para no alargar el cuento, perdimos el vuelo.'),
   ('If I had known, I would have stayed home.', 'Si hubiera sabido, me habría quedado en casa.'),
   ('We ended up laughing about it.', 'Terminamos riéndonos de eso.')],
  [('A', 'You look tired. What happened?', 'Te ves cansado. ¿Qué pasó?'),
   ('B', "You won't believe what happened to me.", 'No vas a creer lo que me pasó.'),
   ('A', 'Tell me everything.', 'Cuéntame todo.'),
   ('B', 'To make a long story short, we missed the flight.', 'Para no alargar el cuento, perdimos el vuelo.'),
   ('A', 'Oh no! And then?', '¡Ay no! ¿Y luego?'),
   ('B', 'In the end, everything worked out fine.', 'Al final, todo salió bien.')]),
 ('Resolver problemas',
  '🛠️',
  [("I'm afraid there's been a mistake.", 'Me temo que hubo un error.'),
   ('I was charged twice for the same thing.', 'Me cobraron dos veces lo mismo.'),
   ('Could you look into it for me?', '¿Podría revisarlo por mí?'),
   ("I'd appreciate it if you could fix this today.", 'Le agradecería si pudiera arreglarlo hoy.'),
   ("That's not what we agreed on.", 'Eso no fue lo que acordamos.'),
   ("I'd like to speak to someone in charge.", 'Quisiera hablar con un encargado.'),
   ('How soon can you sort this out?', '¿Qué tan pronto lo pueden solucionar?'),
   ('Thanks for taking care of it.', 'Gracias por encargarse.')],
  [('A', 'Customer service. How can I help?', 'Servicio al cliente. ¿En qué le ayudo?'),
   ('B', "I'm afraid there's been a mistake.", 'Me temo que hubo un error.'),
   ('A', "I'm sorry. What happened?", 'Lo siento. ¿Qué pasó?'),
   ('B', 'I was charged twice for the same thing.', 'Me cobraron dos veces lo mismo.'),
   ('A', 'Let me check your account.', 'Déjeme revisar su cuenta.'),
   ('B', 'How soon can you sort this out?', '¿Qué tan pronto lo pueden solucionar?')]),
 ('Consejos e hipótesis',
  '🤔',
  [("If I were you, I'd talk to her.", 'Yo que tú, hablaría con ella.'),
   ('What would you do in my place?', '¿Qué harías en mi lugar?'),
   ("You'd better leave early.", 'Es mejor que salgas temprano.'),
   ('I wish I had more free time.', 'Ojalá tuviera más tiempo libre.'),
   ('It might be worth a try.', 'Puede que valga la pena intentarlo.'),
   ('I should have listened to you.', 'Debí haberte escuchado.'),
   ("As long as you're happy, it's fine.", 'Mientras estés contento, está bien.'),
   ('I would rather wait until tomorrow.', 'Prefiero esperar hasta mañana.')],
  [('A', 'I have a problem at work. What would you do in my place?', 'Tengo un problema en el trabajo. ¿Qué harías en mi lugar?'),
   ('B', "If I were you, I'd talk to her.", 'Yo que tú, hablaría con ella.'),
   ('A', "I'm a little nervous about it.", 'Estoy un poco nervioso por eso.'),
   ('B', 'It might be worth a try.', 'Puede que valga la pena intentarlo.')]),
 ('Expresiones comunes',
  '🗣️',
  [("I'm looking forward to seeing you.", 'Tengo muchas ganas de verte.'),
   ("It's not a big deal.", 'No es para tanto.'),
   ('I ran out of time.', 'Se me acabó el tiempo.'),
   ("Let's keep in touch.", 'Sigamos en contacto.'),
   ("I can't make it tonight.", 'No puedo ir esta noche.'),
   ("It's up to you.", 'Tú decides.'),
   ("I'm getting used to it.", 'Me estoy acostumbrando.'),
   ('Give me a hand with this, please.', 'Échame una mano con esto, por favor.')],
  [('A', 'Are you coming to dinner tonight?', '¿Vienes a cenar esta noche?'),
   ('B', "I can't make it tonight.", 'No puedo ir esta noche.'),
   ('A', "That's a shame. Maybe next week?", 'Qué lástima. ¿Tal vez la próxima semana?'),
   ('B', "It's up to you. Let's keep in touch.", 'Tú decides. Sigamos en contacto.')]),
 ('Noticias',
  '📰',
  [('Have you heard the news?', '¿Supiste la noticia?'),
   ('According to the report, prices are going up.', 'Según el informe, los precios están subiendo.'),
   ("It's getting harder to find a job.", 'Cada vez es más difícil encontrar trabajo.'),
   ('I read about it this morning.', 'Lo leí esta mañana.'),
   ('Nobody knows what will happen next.', 'Nadie sabe qué va a pasar después.'),
   ('As far as I know, nothing has changed.', 'Hasta donde sé, nada ha cambiado.'),
   ("It's been all over the news.", 'Ha salido en todas las noticias.'),
   ("I'd rather not talk about politics.", 'Prefiero no hablar de política.')],
  [('A', 'Have you heard the news?', '¿Supiste la noticia?'),
   ('B', 'I read about it this morning.', 'Lo leí esta mañana.'),
   ('A', 'What do you think will happen?', '¿Qué crees que va a pasar?'),
   ('B', 'Nobody knows what will happen next.', 'Nadie sabe qué va a pasar después.')])]

# Niveles. Los identificadores (a, u, c) no deben cambiarse: el progreso guardado depende de ellos.
LEVELS = [
    {"id": 1, "name": "Inicial", "emoji": "🌱", "desc": "Desde cero. Frases muy cortas, ideal para niños."},
    {"id": 2, "name": "Básico", "emoji": "🌿", "desc": "Frases sencillas para el día a día."},
    {"id": 4, "name": "Pre-intermedio", "emoji": "🪴", "desc": "Hablar del pasado, pedir cosas y resolver situaciones comunes."},
    {"id": 3, "name": "Intermedio", "emoji": "🌳", "desc": "Frases más largas y conversaciones reales."},
    {"id": 5, "name": "Avanzado", "emoji": "🏔️", "desc": "Expresiones naturales, trabajo, historias y opiniones."},
]

UNITS = []
for prefix, level, raw in (("a", 1, _L1), ("u", 2, _RAW), ("b", 4, _L2B), ("c", 3, _L3), ("d", 5, _L5)):
    for n, (title, emoji, phrases, lines) in enumerate(raw, start=1):
        uid = f"{prefix}{n}"
        UNITS.append({
            "id": uid,
            "level": level,
            "title": title,
            "emoji": emoji,
            "phrases": [
                {"id": f"{uid}p{i}", "en": en, "es": es}
                for i, (en, es) in enumerate(phrases, start=1)
            ],
            "dialogue": {"id": f"{uid}d", "lines": [list(line) for line in lines]},
        })

# Pares de sonidos que suelen confundir los hispanohablantes.
_PAIRS = [
    ("ship", "sheep", "En 'ship' la vocal es corta y relajada. En 'sheep' es larga, como sonriendo."),
    ("live", "leave", "'live' es corta; 'leave' es larga: liiiv."),
    ("this", "these", "'this' termina en s suave y vocal corta; 'these' es larga y termina en z."),
    ("cat", "cut", "En 'cat' abre bien la boca; en 'cut' es un sonido corto, casi una 'a' apagada."),
    ("very", "berry", "Para la 'v' los dientes de arriba tocan el labio de abajo. La 'b' junta los dos labios."),
    ("vote", "boat", "'vote' empieza con dientes en el labio; 'boat' con los labios cerrados."),
    ("three", "tree", "Para 'th' saca un poco la lengua entre los dientes y sopla."),
    ("think", "sink", "'think' lleva la lengua entre los dientes; 'sink' es una 's' normal."),
    ("they", "day", "En 'they' la lengua toca los dientes y vibra; 'day' es una 'd' seca."),
    ("chair", "share", "'chair' es como la 'ch' del español; 'share' es más suave, como pidiendo silencio: shhh."),
    ("watch", "wash", "'watch' termina en 'ch'; 'wash' termina en 'shhh'."),
    ("yellow", "jello", "'yellow' empieza suave como una 'i'; 'jello' empieza fuerte, como 'dch'."),
]
PAIRS = [{"id": f"m{i}", "a": a, "b": b, "tip": tip} for i, (a, b, tip) in enumerate(_PAIRS, start=1)]
